[build]
  command = "echo 'Using static files only' && mkdir -p public && cp demo.html public/index.html"
  publish = "public"

# Redirect all routes to the demo for now
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"